title:              Tidbits of Everything AI
email:              gathaa@gmail.com
description:        A Blog Where I Talk About AI Things Running Wild on The Internet.
author:             Gatha Varma
baseurl:            ""
url:                "https://plau51ble.github.io"
remote_theme:       jekyll-theme-clean-blog

# Social Profiles
twitter_username:   GathaVarma
github_username:    plau51ble
#facebook_username:  StartBootstrap
#instagram_username:  
linkedin_username:  gatha-varma

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
